name: 🔗 GHA

on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:
    inputs:
      build_windows:
        description: "Build Windows"
        type: boolean
        default: true
      build_linux:
        description: "Build Linux"
        type: boolean
        default: true
      build_macos:
        description: "Build macOS"
        type: boolean
        default: false
      build_ios:
        description: "Build iOS"
        type: boolean
        default: false
      build_android:
        description: "Build Android"
        type: boolean
        default: false
      build_web:
        description: "Build Web"
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  # First stage: Only static checks

  static-checks:
    if: ${{ !vars.DISABLE_GODOT_CI || github.run_attempt > 1 || github.event_name == 'workflow_dispatch' }}
    name: 📊 Static checks
    uses: ./.github/workflows/static_checks.yml

  # Helper condition:
  # - Always allow Windows on push/PR
  # - For workflow_dispatch, respect inputs

  android-build:
    name: 🤖 Android
    needs: static-checks
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.build_android) ||
      (github.event_name != 'workflow_dispatch' && false)
    uses: ./.github/workflows/android_builds.yml
    secrets:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

  ios-build:
    name: 🍏 iOS
    needs: static-checks
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.build_ios) ||
      (github.event_name != 'workflow_dispatch' && false)
    uses: ./.github/workflows/ios_builds.yml

  linux-build:
    name: 🐧 Linux
    needs: static-checks
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.build_linux) ||
      (github.event_name != 'workflow_dispatch')
    uses: ./.github/workflows/linux_builds.yml
    with:
      changed-files: ${{ needs.static-checks.outputs.changed-files }}

  macos-build:
    name: 🍎 macOS
    needs: static-checks
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.build_macos) ||
      (github.event_name != 'workflow_dispatch' && false)
    uses: ./.github/workflows/macos_builds.yml

  windows-build:
    name: 🏁 Windows
    needs: static-checks
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.build_windows) ||
      (github.event_name != 'workflow_dispatch')
    uses: ./.github/workflows/windows_builds.yml

  web-build:
    name: 🌐 Web
    needs: static-checks
    if: |
      (github.event_name == 'workflow_dispatch' && inputs.build_web) ||
      (github.event_name != 'workflow_dispatch' && false)
    uses: ./.github/workflows/web_builds.yml
